// AUTO-GENERATED by scripts/build.mjs — do not edit manually
// sahih-al-bukhari v3.1.7
// Fetches data/bukhari.json.gz from CDN. Works in React, Vue, Vite, webpack.

const CDN_FILE = 'https://cdn.jsdelivr.net/npm/sahih-al-bukhari@3.1.7/data/bukhari.json.gz';

function _build(hadiths, meta) {
  return Object.assign([], hadiths, {
    metadata:     meta.metadata,
    chapters:     meta.chapters,
    getByChapter: (id) => hadiths.filter(h => h.chapterId === id),
    get:          (id) => hadiths.find(h => h.id === id),
    search:       (q, limit = 0) => {
      const ql = q.toLowerCase();
      const r  = hadiths.filter(h =>
        h.english?.text?.toLowerCase().includes(ql) ||
        h.english?.narrator?.toLowerCase().includes(ql)
      );
      return limit > 0 ? r.slice(0, limit) : r;
    },
    getRandom: () => hadiths[Math.floor(Math.random() * hadiths.length)],
  });
}

export class Bukhari {
  constructor(data) { return _build(data.hadiths, data); }
}

let _cache = null, _promise = null;

export function loadBukhari() {
  if (_cache)   return Promise.resolve(_cache);
  if (_promise) return _promise;
  _promise = fetch(CDN_FILE)
    .then(r => r.arrayBuffer())
    .then(buf => {
      const stream = new DecompressionStream('gzip');
      const writer = stream.writable.getWriter();
      const reader = stream.readable.getReader();
      writer.write(new Uint8Array(buf)); writer.close();
      const chunks = [];
      return (function pump() {
        return reader.read().then(({ done, value }) => {
          if (done) {
            const text = new TextDecoder().decode(new Uint8Array(chunks.reduce((a,b)=>[...a,...b],[])));
            _cache = _build(JSON.parse(text).hadiths, JSON.parse(text));
            return _cache;
          }
          chunks.push(value); return pump();
        });
      })();
    });
  return _promise;
}

export default loadBukhari();
